_target_: models.tokenizer.Tokenizer
vocab_size: 512
loss_weights:
  commitment: 0.25
  codebook: 1.0
config:
  in_channels: 12  # 4帧×3通道
  z_channels: 256
  num_res_blocks: 2
  channel_multipliers: [1, 2, 4]
  resolution: 64
