_target_: models.world_model.WorldModel
obs_vocab_size: ${tokenizer.vocab_size}
act_vocab_size: 4  # 俄罗斯方块动作：左移、右移、旋转、下落
config:
  tokens_per_block: 16  # 每个block包含的token数
  max_blocks: 32  # 最大block数，sequence_length = 16*32=512
  attention: causal  # 因果注意力
  num_layers: 8
  num_heads: 8
  embed_dim: 512
  embed_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1
